podTemplate(yaml: '''
    apiVersion: v1
    kind: Pod
    spec:
        containers:
        - name: script
          image: 2615738927488.dkr.ecr.us-east-1.amazonaws.com/imagem/create_app_cards_private:newjenkins
          imagePullPolicy: Always
          command:
            - sleep
          args:
            - 99d
          volumeMounts:
          - mountPath: /root/.ssh
            name: jenkins-sshkey
          - mountPath: /volumes
            name: volumes
        volumes:
        - name: jenkins-sshkey
          nfs:
            path: /jenkins-sshkey
            server: 10.0.64.38
        - name: volumes
          nfs:
            path: /volumes/logs
            server: 10.0.64.38    
''') {
    
    node(POD_LABEL) {
        container('script') {
            sh "python3 /main.py ${EMISSOR} ${AMBIENTE} ${NEW_BRANCH}"
        }
    }
}  